Fogl 1658 - Update foglamp-south-am2315
foglamp/foglamp-south-am2315 pull request #2
Opened 2018-08-22 12:43 UTC by amarendra-dianomic

2018-08-27 06:24 UTC, praveen-garg requested changes
remove _plugin_stop  it  neither has real code to execute nor a contract method.

2018-08-27 06:24 UTC, praveen-garg commented on python/foglamp/plugins/south/am2315/am2315.py
> +        'order': '2'
it should be 1

2018-08-27 06:24 UTC, praveen-garg commented on python/foglamp/plugins/south/am2315/am2315.py
> +        'order': '1'
it should be 2

2018-08-27 06:24 UTC, praveen-garg commented on python/foglamp/plugins/south/am2315/am2315.py
>      },
make plugin name  to load readonly

2018-08-27 06:24 UTC, praveen-garg commented on python/foglamp/plugins/south/am2315/am2315.py
> +    if 'pollInterval' in diff or 'i2cAddress' in diff:
what about assetPrefix? did we test restart?

2018-08-27 10:32 UTC, Singhal-Vaibhav requested changes
The plugin goes into a state of infinite loop when i2cAddress us updated. Syslog keep producing these errors:
```
ERROR: server: foglamp.services.south.server: Key error plugin am : 'bus'#012Traceback (most recent call last):#012  File "/home/pi/FogLAMP/python/foglamp/services/south/server.py", line 167, in _exec_plugin_poll#012    data = self._plugin.plugin_poll(self._plugin_handle)#012  File "/home/pi/FogLAMP/python/foglamp/plugins/south/am2315/am2315.py", line 103, in plugin_poll#012    bus = handle["bus"]#012KeyError: 'bus'
```

2018-08-28 12:38 UTC, ashish-jabble commented on python/foglamp/plugins/south/am2315/am2315.py
>          new_handle = copy.deepcopy(new_config)
```
plugin_shutdown(handle)
new_handle = plugin_init(new_config)
new_handle['restart'] = 'yes'
_LOGGER.info(“Restarting AM2315 plugin due to change in configuration key [{}]“.format(‘, ’.join(diff)))
```

2018-08-28 12:39 UTC, ashish-jabble commented on python/foglamp/plugins/south/am2315/am2315.py
>          time_stamp = str(datetime.datetime.now(tz=datetime.timezone.utc))
`utils.local_timestamp()`

2018-08-30 14:17 UTC, Singhal-Vaibhav submitted a review, later dismissed

2018-08-30 14:22 UTC, praveen-garg requested changes

2018-08-30 14:22 UTC, praveen-garg commented on README.rst
> +# foglamp-south-am2315
rst fix needed

2018-08-30 14:22 UTC, praveen-garg commented on python/foglamp/plugins/south/am2315/am2315.py
> +        'default': 'am2315/%M/',
do we want this `%M` to be replaced by i2c address? @ashwinscale  @billehunt  please confirm

2018-08-30 14:22 UTC, praveen-garg commented on python/foglamp/plugins/south/am2315/am2315.py
> +        'order': '2'
let's add some min value ? I hope 0 is handled by south server

2018-08-30 14:22 UTC, praveen-garg commented on python/foglamp/plugins/south/am2315/am2315.py
> +        new_handle['restart'] = 'yes'
do we need to restart for `pollInterval`

2018-09-05 11:22 UTC, amarendra-dianomic commented
@Singhal-Vaibhav #3 merged into this PR. Pl check.

2018-09-05 13:11 UTC, praveen-garg submitted a review, later dismissed
There are few comments which are not addressed. let's handle them in next PR with preinst script removal!

2018-09-05 13:58 UTC, Singhal-Vaibhav requested changes

2018-09-05 13:58 UTC, Singhal-Vaibhav commented on python/foglamp/plugins/south/am2315/am2315.py
> +        'minimum': 1000
Should be a string

2018-09-06 06:02 UTC, amarendra-dianomic commented
@Singhal-Vaibhav minimum fixed. Pl check.

2018-09-06 11:03 UTC, Singhal-Vaibhav approved these changes
Code wise look good

2018-09-06 11:04 UTC, merged